# Generated by Django 5.0.7 on 2024-12-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='achieveuser',
            managers=[
            ],
        ),
    ]
