# Generated by Django 5.0.7 on 2024-12-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_achieveuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achieveuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
