# Generated by Django 5.0.7 on 2024-12-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_achieveuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='content',
            new_name='topic',
        ),
    ]
