# Generated by Django 5.0.7 on 2024-12-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_module_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='image',
            new_name='course_image',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='image',
            new_name='module_image',
        ),
    ]
