# Generated by Django 5.0.7 on 2024-12-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_image_course_course_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='slug',
            new_name='course_slug',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='slug',
            new_name='module_slug',
        ),
    ]
