# Generated by Django 5.0.7 on 2024-12-14 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
