# Generated by Django 5.0.7 on 2024-12-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_answer_answered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='attempts_allowed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='attempts_taken',
            field=models.IntegerField(null=True),
        ),
    ]
