# Generated by Django 5.0.7 on 2024-12-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_quiz_attempts_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('answered_by', 'question')},
        ),
    ]
