# Generated by Django 5.0.7 on 2024-12-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_question_final_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='final_score',
        ),
        migrations.AddField(
            model_name='quiz',
            name='final_score',
            field=models.IntegerField(null=True),
        ),
    ]
