# Generated by Django 5.0.7 on 2024-12-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_question_final_score_quiz_final_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
    ]
