# Generated by Django 5.0.7 on 2024-12-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_question_question_time_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
