# Generated by Django 5.0.7 on 2024-12-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_answer_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='topic',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashcard_question', models.TextField()),
                ('flashcard_answer', models.TextField()),
                ('flashcard_image', models.ImageField(blank=True, null=True, upload_to='flashcard_images')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='main.module')),
            ],
        ),
    ]
