# Generated by Django 5.0.7 on 2025-01-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_course_description_alter_module_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='flashcard_image',
        ),
    ]
