# Generated by Django 5.0.7 on 2025-01-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_flashcard_flashcard_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='flashcard_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='flashcard_question',
            new_name='question',
        ),
    ]
