# Generated by Django 5.0.7 on 2025-01-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_externallink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externallink',
            old_name='title',
            new_name='description',
        ),
    ]
