# Generated by Django 5.0.7 on 2025-02-04 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_course_course_slug_remove_module_module_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answered_at',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answered_by',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='answers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.answer'),
        ),
    ]
