# Generated by Django 5.0.7 on 2025-02-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_answer_answered_at_remove_answer_answered_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='attempts_taken',
            new_name='total_attempts',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='answers',
        ),
    ]
