# Generated by Django 5.0.7 on 2025-02-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_attempts_taken_quizattempt_total_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='total_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
