# Generated by Django 5.0.7 on 2025-02-10 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_quizattempt_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='main.quizattempt'),
        ),
    ]
