# Generated by Django 5.0.7 on 2025-02-24 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_image',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.comment'),
        ),
    ]
