# Generated by Django 5.0.7 on 2025-02-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_comment_image_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment_image',
            new_name='CommentImage',
        ),
    ]
