# Generated by Django 5.0.7 on 2025-02-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_rename_comment_image_commentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/'),
        ),
    ]
