# Generated by Django 5.0.7 on 2025-03-09 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_courseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='enrolled_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
