# Generated by Django 5.0.7 on 2025-03-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_courseenrollment_enrolled_by'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='unique_enrollment'),
        ),
    ]
