# Generated by Django 5.0.7 on 2025-04-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_courseenrollment_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
