# Generated by Django 5.0.7 on 2025-04-20 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_notification_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='course',
        ),
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.comment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='enrollment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.courseenrollment'),
        ),
    ]
