# Generated by Django 5.0.7 on 2025-04-20 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_remove_notification_course_notification_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_notifications', to='main.comment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='enrollment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_notifications', to='main.courseenrollment'),
        ),
    ]
