# Generated by Django 5.0.7 on 2025-05-04 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_notification_reciever'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lesson',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_notifications', to='main.module'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reciever',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
